/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rc.logging.demo;

import com.ringcentral.RestClient;
import com.ringcentral.RestException;
import java.io.IOException;
import java.util.logging.Level;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, RestException {
        RestClient.logger.setLevel(Level.FINE);
        var rc = new RestClient("fake", "fake", "https://platform.ringcentral.com");
        rc.authorize("fake", "", "fake");
    }
}
